---
- include:              '../tasks/lines_in_files.yml'
  vars:
    lines_in_files:
      - line:           "{{ line_spec.line }}"
        regexp:         "{{ line_spec.regexp }}"
        dest:           "{{ main_config }}"
  with_items:           "{{ lines_in_main_config }}"
  loop_control:
    loop_var:           'line_spec'
  register:             configure_postfix_result
