---
- lineinfile:
    line:               "{{ line_spec.line }}"
    regexp:             "{{ line_spec.regexp }}"
    dest:               "{{ opendkim_conf }}"
    state:              'present'
  with_items:           "{{ lines_in_opendkim_conf }}"
  loop_control:
    loop_var:           'line_spec'
  register:             configure_opendkim_result
