---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/add_users_to_groups.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        'register_client_certs.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/shell_commands_ignore_change.yml'
  when:                 template_files_result.changed
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 add_users_to_groups_result.changed
                        or template_files_result.changed
                        or install_files_result.changed
