---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/create_files.yml'
- include:              'register_client_certs.yml'
- include:              'configure_postfix.yml'
- include:              'configure_opendkim.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/shell_commands_ignore_result.yml'
  when:                 template_files_result.changed
- include:              '../tasks/start_services.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or template_files_result.changed
                        or configure_opendkim_result.changed
                        or configure_postfix_result.changed
