---
- command:              chpasswd <<< "{{ smtp_user }}:{{ lookup('community.general.passwordstore', 'aaron/{{ groups['mail-server'][0] }}/{{ smtp_user }}') }}"
  become_user:          'root'
  with_items:           "{{ smtp_users }}"
  loop_control:
    loop_var:           smtp_user
  register:             set_smtp_user_passwords_result
  changed_when:         false
